services:

    platform.excelService:
        class: PlatformBundle\Services\ExcelService
        arguments: ['@phpoffice.spreadsheet']

    platform.purge:
        class: PlatformBundle\Services\PurgeService
        arguments: ['@doctrine.orm.entity_manager', 60]
