services:
#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    platform.excelService:
        class: PlatformBundle\Services\ExcelService
        arguments: ['@phpexcel']

    platform.purge:
        class: PlatformBundle\Services\PurgeService
        arguments: ['@doctrine.orm.entity_manager', 60]
