<?php

namespace PlatformBundle\Repository;

/**
 * CommandProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandProductRepository extends \Doctrine\ORM\EntityRepository
{
}
