<?php

namespace PlatformBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTreatementAndDate($days)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.treat = :true')
            ->where('a.treatmentDate < :date')
            ->setParameter('date', new \Datetime('-' . $days . ' day'))

        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByTreatmentOrderDate()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.treat = false')
            ->orderBy('a.creationDate', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByTreatedOrderDate()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.treat = true')
            ->orderBy('a.creationDate', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByUserOrderDate($user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.user = :user')
            ->setParameter('user', $user)
            ->orderBy('a.creationDate', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
