<?php

namespace PlatformBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoryOfProduct($category)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.category = :category')
            ->setParameter('category', $category);
    }
}
